### PR TITLE
Include return code FIxes #81

### LINKED ISSUE #81: Error should include return_code from typhoeus
When a requested service is not running, LHC returns a Timeout:
```
get http://localhost:4000//tour_assignments
Options: {:params=>{:sort_by=>"customer_name", :sort_order=>"asc", :employee_login=>"DIR13590", :offset=>0, :limit=>25}, :url=>"http://localhost:4000//tour_assignments", :interceptors=>[#<Class:0x007fc14104a6f0>, #<Class:0x007fc14104a358>, #<Class:0x007fc141049d18>, #<Class:0x007fc141048a58>, #<Class:0x007fc141048058>, #<Class:0x007fc14103be48>], :cache=>true, :cache_expires_in=>300 seconds, :cache_race_condition_ttl=>5 seconds, :cache_key=>"LHS_REQUEST_CYCLE_CACHE(v1) GET http://localhost:4000//tour_assignments?{:sort_by=>\"customer_name\", :sort_order=>\"asc\", :employee_login=>\"DIR13590\", :offset=>0, :limit=>25} REQUEST=1496043895.6987321#8 HEADERS=-477230137558272738", :cached_methods=>[:get]}
Headers: {"User-Agent"=>"Typhoeus - https://github.com/typhoeus/typhoeus"}
Response Code: 0

LHC::Timeout
```

But it shold display a 'connection failed' like curl:
```
$ curl http://localhost:4000//tour_assignments
curl: (7) Failed to connect to localhost port 4000: Connection refused
```

The information would be there:
```
From: /Users/flavio/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/lhc-5.0.2/lib/lhc/request.rb @ line 102 LHC::Request#on_complete:

     98: def on_complete(response)
     99:   self.response ||= LHC::Response.new(response, self)
    100:   iprocessor.intercept(:after_response, self.response)
    101:   binding.pry unless self.response.success?
 => 102:   handle_error(self.response) unless self.response.success?
    103: end

[1] pry(#<LHC::Request>)> response.options
=> {:httpauth_avail=>0,
 :total_time=>0.005363,
 :starttransfer_time=>0.0,
 :appconnect_time=>0.0,
 :pretransfer_time=>0.0,
 :connect_time=>0.0,
 :namelookup_time=>0.005137,
 :redirect_time=>0.0,
 :effective_url=>
  "http://localhost:4000//tour_assignments?sort_by=customer_name&sort_order=asc&employee_login=DIR13590&offset=0&limit=25",
 :primary_ip=>"",
 :response_code=>0,
 :request_size=>0,
 :redirect_count=>0,
 :return_code=>:couldnt_connect,
 :response_headers=>"",
 :response_body=>"",
 :debug_info=>#<Ethon::Easy::DebugInfo:0x007fc13939cb58 @messages=[]>}
[2] pry(#<LHC::Request>)> response.return_code
=> :couldnt_connect
```

### PR DESCRIPTION
**Pull request by fpellanda**

### CODE REVIEW

File: spec/request/error_handling_spec.rb [hunk 1]
```diff
@@ -14,6 +14,7 @@ def expect_status_code(status_code)
     end
 
     it 'raises errors for anything but 2XX response codes' do
+      expect_status_code(0)   { to_fail_with(LHC::UnknownError) }
```
Comment (spape) [inline spec/request/error_handling_spec.rb]: Shouldn't this be LHC::Timeout, just like above?

File: lib/lhc/response.rb [hunk 2]
```diff
@@ -51,7 +51,7 @@ def time
   end
 
   def timeout?
-    raw.timed_out?
+    options[:return_code] == :operation_timedout
```
Comment (spape) [inline lib/lhc/response.rb]: Please keep abstraction and concrete coupling!
That was covered by https://github.com/typhoeus/typhoeus/blob/181834e2483d392d0f7ab0cd17f544cd252c7b2f/lib/typhoeus/response/status.rb#L68 already

File: lib/lhc/error.rb [hunk 3]
```diff
@@ -58,7 +58,8 @@ def to_s
     debug << [request.method, request.url].map { |str| fix_invalid_encoding(str) }.join(' ')
     debug << "Options: #{request.options}"
     debug << "Headers: #{request.headers}"
-    debug << "Response Code: #{response.code}"
+    debug << "Response Code: #{response.code} (#{response.options[:return_code]})"
+    debug << "Repsonse Options: #{response.options}"
```
Comment (spape) [inline lib/lhc/error.rb]: I've give the error debug output more attention, we might want to test it too...
see: https://github.com/local-ch/lhs/blob/forward-errors-to-nested-data/spec/data/inspect_spec.rb#L39

File: spec/request/error_handling_spec.rb (hunk 1 above)
Comment (fpellanda) [inline spec/request/error_handling_spec.rb]: As far as I understood: Status 0 means, that there is no response. This can be for different reasons (which is described in `options[:return_code]`. This can be a network error or maybe the DNS name could not be resolved - which is not a timeout.

File: lib/lhc/response.rb (hunk 2 above)
Comment (fpellanda) [inline lib/lhc/response.rb]: Hm, right. Did not see that, but I wonder why then I got a Timeout error in SalesButler, where no timeout was. I'll investigate.

File: spec/error/to_s_spec.rb [hunk 4]
```diff
@@ -40,5 +40,36 @@
     end
     # the other cases cannot be tested (for example what happens if the headers contain invalid data)
     # because the mocking framework triggers the encoding error already
+
+    context 'some mocked ersponse' do
```
Comment (spape) [inline spec/error/to_s_spec.rb]: typo: `response`

File: spec/error/to_s_spec.rb [hunk 5]
```diff
@@ -40,5 +40,36 @@
...
+               method: 'GET',
+               url: 'http://example.com/singularity',
+               headers: { 'REQUEST' => 'headers' },
+               options: { request: 'options' })
+      end
+
+      let(:response) do
+        double('response',request: request,
+                       code: 404,
+                       options: { return_code: 'returncode', otherooption: 123 },
```
Comment (spape) [inline spec/error/to_s_spec.rb]: Make a real returncode example, not just a placeholder. Test are Living documentation.

File: spec/error/to_s_spec.rb [hunk 6]
```diff
@@ -40,5 +40,36 @@
     end
     # the other cases cannot be tested (for example what happens if the headers contain invalid data)
     # because the mocking framework triggers the encoding error already
+
+    context 'some mocked ersponse' do
+      let(:request) do
+        double('request',
+               method: 'GET',
+               url: 'http://example.com/singularity',
+               headers: { 'REQUEST' => 'headers' },
```
Comment (spape) [inline spec/error/to_s_spec.rb]: Please try make real examples with headers. Tests are Living documentation.

File: spec/error/to_s_spec.rb [hunk 7]
```diff
@@ -40,5 +40,36 @@
...
+               options: { request: 'options' })
```
Comment (spape) [inline spec/error/to_s_spec.rb]: Please try make real examples with options. Tests are Living documentation.

File: spec/error/to_s_spec.rb (hunk 5 above)
Comment (spape) [inline spec/error/to_s_spec.rb]: The same for otherooption (typoe btw) and body.
